library verilog;
use verilog.vl_types.all;
entity Processador is
    port(
        clk             : in     vl_logic;
        rst             : in     vl_logic;
        instr_mem_data15: in     vl_logic;
        instr_mem_data14: in     vl_logic;
        instr_mem_data13: in     vl_logic;
        instr_mem_data12: in     vl_logic;
        instr_mem_data11: in     vl_logic;
        instr_mem_data10: in     vl_logic;
        instr_mem_data9 : in     vl_logic;
        instr_mem_data8 : in     vl_logic;
        instr_mem_data7 : in     vl_logic;
        instr_mem_data6 : in     vl_logic;
        instr_mem_data5 : in     vl_logic;
        instr_mem_data4 : in     vl_logic;
        instr_mem_data3 : in     vl_logic;
        instr_mem_data2 : in     vl_logic;
        instr_mem_data1 : in     vl_logic;
        instr_mem_data0 : in     vl_logic;
        data_mem_data_in15: in     vl_logic;
        data_mem_data_in14: in     vl_logic;
        data_mem_data_in13: in     vl_logic;
        data_mem_data_in12: in     vl_logic;
        data_mem_data_in11: in     vl_logic;
        data_mem_data_in10: in     vl_logic;
        data_mem_data_in9: in     vl_logic;
        data_mem_data_in8: in     vl_logic;
        data_mem_data_in7: in     vl_logic;
        data_mem_data_in6: in     vl_logic;
        data_mem_data_in5: in     vl_logic;
        data_mem_data_in4: in     vl_logic;
        data_mem_data_in3: in     vl_logic;
        data_mem_data_in2: in     vl_logic;
        data_mem_data_in1: in     vl_logic;
        data_mem_data_in0: in     vl_logic;
        instr_addr7     : out    vl_logic;
        instr_addr6     : out    vl_logic;
        instr_addr5     : out    vl_logic;
        instr_addr4     : out    vl_logic;
        instr_addr3     : out    vl_logic;
        instr_addr2     : out    vl_logic;
        instr_addr1     : out    vl_logic;
        instr_addr0     : out    vl_logic;
        data_addr7      : out    vl_logic;
        data_addr6      : out    vl_logic;
        data_addr5      : out    vl_logic;
        data_addr4      : out    vl_logic;
        data_addr3      : out    vl_logic;
        data_addr2      : out    vl_logic;
        data_addr1      : out    vl_logic;
        data_addr0      : out    vl_logic;
        data_mem_data_out15: out    vl_logic;
        data_mem_data_out14: out    vl_logic;
        data_mem_data_out13: out    vl_logic;
        data_mem_data_out12: out    vl_logic;
        data_mem_data_out11: out    vl_logic;
        data_mem_data_out10: out    vl_logic;
        data_mem_data_out9: out    vl_logic;
        data_mem_data_out8: out    vl_logic;
        data_mem_data_out7: out    vl_logic;
        data_mem_data_out6: out    vl_logic;
        data_mem_data_out5: out    vl_logic;
        data_mem_data_out4: out    vl_logic;
        data_mem_data_out3: out    vl_logic;
        data_mem_data_out2: out    vl_logic;
        data_mem_data_out1: out    vl_logic;
        data_mem_data_out0: out    vl_logic;
        mem_rd          : out    vl_logic;
        mem_wr          : out    vl_logic
    );
end Processador;
